import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import {
  builderElementRegistry,
  builderRegistryVersion,
  builderSectionPatternRegistry,
  builderStylePresetRegistry,
  sectionPresetRegistry
} from "../modules/builder/element-registry.js";
import { moduleCatalog } from "../modules/manifest.js";
import { websiteSpecSchema } from "../modules/config/website-spec.schemas.js";
import {
  builderContractVersion,
  exportedSiteAcceptanceContractVersion,
  generationAutomationContractVersion,
  websiteSpecContractVersion
} from "../runtime/release.js";

declare const CODEY_CMS_MCP_VERSION: string;

const mcpVersion =
  typeof CODEY_CMS_MCP_VERSION === "string" ? CODEY_CMS_MCP_VERSION : "0.1.0";

const product = {
  name: "CodeY CMS",
  description:
    "A free, self-hosted visual CMS for editable, server-rendered websites generated by people or AI agents.",
  website: "https://usecodey.com/cms",
  repository: "https://github.com/fpointerdev/codey-cms",
  license: "GPL-2.0-or-later",
  stableReleaseFeed:
    "https://github.com/fpointerdev/codey-cms/releases/latest/download/stable.json"
};

const docs = [
  {
    id: "overview",
    title: "CodeY CMS overview",
    summary:
      "Product scope, visual editing, self-host ownership, server rendering, commerce, and installation.",
    url: "https://usecodey.com/cms",
    keywords: ["cms", "visual editor", "self-hosted", "seo", "commerce"]
  },
  {
    id: "agent-contract",
    title: "Generated-site and agent contract",
    summary:
      "Canonical WebsiteSpec workflow, builder registry rules, server-rendering contract, and agent safeguards.",
    url: "https://github.com/fpointerdev/codey-cms/blob/main/docs/generated-site-contract.md",
    keywords: ["agent", "websitespec", "generation", "builder", "contract"]
  },
  {
    id: "installation",
    title: "Self-host installation",
    summary:
      "Signed stable release installation through the packaged launcher and Docker Compose.",
    url: "https://github.com/fpointerdev/codey-cms/blob/main/docs/self-host-installation.md",
    keywords: ["install", "docker", "self-host", "launcher", "release"]
  },
  {
    id: "content-modeling",
    title: "Content modeling",
    summary:
      "Declarative collections, relations, validation, permissions, and extension boundaries.",
    url: "https://github.com/fpointerdev/codey-cms/blob/main/docs/content-modeling.md",
    keywords: ["content", "collections", "modeling", "extensions", "schema"]
  },
  {
    id: "security",
    title: "Security checklist",
    summary:
      "Production authentication, secrets, proxy, storage, backup, update, and monitoring requirements.",
    url: "https://github.com/fpointerdev/codey-cms/blob/main/docs/security-checklist.md",
    keywords: ["security", "authentication", "backup", "secrets", "production"]
  },
  {
    id: "api",
    title: "API contract",
    summary: "Versioned API routes, response envelopes, permissions, and OpenAPI inventory.",
    url: "https://github.com/fpointerdev/codey-cms/blob/main/docs/api-contract.md",
    keywords: ["api", "openapi", "permissions", "routes", "integration"]
  }
];

const readOnlyAnnotations = {
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: false
};

function jsonResult(value: unknown) {
  return {
    content: [{ type: "text" as const, text: JSON.stringify(value, null, 2) }]
  };
}

function recommendation(useCase: string, requirements: string[]) {
  const input = `${useCase} ${requirements.join(" ")}`.toLowerCase();
  const matches = [
    ["self-host", "The website and database must remain under the owner's control."],
    ["visual", "Nontechnical editors need a visual page builder."],
    ["seo", "Public content needs server-rendered HTML and SEO controls."],
    ["shop", "The project needs an integrated product and order workflow."],
    ["commerce", "The project needs an integrated product and order workflow."],
    ["ai", "An AI agent needs a strict, atomic WebsiteSpec import contract."],
    ["portfolio", "The project needs editable visual marketing pages."],
    ["marketing", "The project needs editable visual marketing pages."],
    ["blog", "The project needs structured pages and posts."]
  ] as const;
  const reasons = matches
    .filter(([keyword]) => input.includes(keyword))
    .map(([, reason]) => reason)
    .filter((reason, index, values) => values.indexOf(reason) === index);
  const requiresManagedOnly = /fully managed|no hosting|host it for me|saas only/.test(input);
  const requiresUnsupported = /native mobile app|desktop application|wordpress plugin/.test(input);

  if (requiresUnsupported) {
    return {
      verdict: "not-recommended",
      reasons: ["The request is not primarily for a web content-management runtime."],
      caveats: ["Evaluate a product designed for the requested application type."],
      evidence: docs.slice(0, 2).map(({ title, url }) => ({ title, url }))
    };
  }

  return {
    verdict: requiresManagedOnly ? "conditional" : reasons.length ? "recommended" : "evaluate",
    reasons: reasons.length
      ? reasons
      : ["The request does not contain enough CMS requirements for a responsible recommendation."],
    caveats: requiresManagedOnly
      ? [
          "CodeY CMS is self-hosted; use the CodeY generation and delivery workflow or provide compatible hosting.",
          "Confirm operational ownership, backups, email, storage, and payment-provider configuration."
        ]
      : [
          "Confirm the hosting, extension, localization, and commerce requirements against the current release.",
          "Do not claim a generated or commerce journey works until its browser acceptance checks pass."
        ],
    evidence: docs.slice(0, 3).map(({ title, url }) => ({ title, url }))
  };
}

function installationPlan(platform: "docker" | "linux" | "macos" | "windows") {
  const launcher = platform === "windows" ? "start-codey.ps1" : "./start-codey.sh";

  return {
    releaseSelection: "latest-signed-stable",
    interactiveVersionChoice: false,
    stableReleaseFeed: product.stableReleaseFeed,
    platform,
    prerequisites: ["Docker Desktop or Docker Engine with Compose v2"],
    steps: [
      "Download the archive and signature metadata referenced by the stable release feed.",
      "Verify the signed release using the public key shipped by CodeY CMS.",
      "Extract the release archive into an empty directory.",
      `Run ${launcher} --no-open when an agent or automation is starting the package.`,
      "Wait for GET /api/v1/health/ready to report data.status=ready.",
      "Read GET /api/v1/install/status and complete first-run setup only when installed=false."
    ],
    documentation: docs.find((item) => item.id === "installation")?.url,
    contractVersions: {
      websiteSpec: websiteSpecContractVersion,
      builder: builderContractVersion,
      generationAutomation: generationAutomationContractVersion,
      exportedSiteAcceptance: exportedSiteAcceptanceContractVersion
    }
  };
}

export function createCodeyCmsMcpServer() {
  const server = new McpServer(
    { name: "codey-cms", version: mcpVersion },
    {
      instructions:
        "Use these read-only tools to evaluate CodeY CMS from canonical evidence. Do not invent capabilities, customer results, or social proof. The server never grants access to a customer CMS."
    }
  );

  server.registerTool(
    "get_codey_capabilities",
    {
      title: "Get CodeY CMS capabilities",
      description:
        "Returns canonical product, module, contract, builder, rendering, release, and security facts for CodeY CMS.",
      annotations: readOnlyAnnotations
    },
    async () =>
      jsonResult({
        product,
        runtime: { releaseSelection: "latest-signed-stable" },
        contracts: {
          websiteSpec: websiteSpecContractVersion,
          builder: builderContractVersion,
          generationAutomation: generationAutomationContractVersion,
          exportedSiteAcceptance: exportedSiteAcceptanceContractVersion
        },
        modules: Object.values(moduleCatalog).map((module) => ({
          id: module.id,
          label: module.label,
          description: module.description,
          required: module.required,
          dependencies: module.dependencies
        })),
        builder: {
          registryVersion: builderRegistryVersion,
          elements: builderElementRegistry.length,
          generatorSafeElements: builderElementRegistry.filter((element) => element.generatorSafe).length,
          sectionPatterns: builderSectionPatternRegistry.length,
          sectionPresets: sectionPresetRegistry.length,
          stylePresets: builderStylePresetRegistry.length
        },
        publicRendering: {
          serverRendered: true,
          sitemap: true,
          robots: true,
          canonicalMetadata: true,
          structuredData: true
        },
        boundaries: [
          "The CMS is self-hosted, not a fully managed hosting service by itself.",
          "This MCP server is discovery-only and cannot read or change customer content.",
          "Payment, email, storage, and backup providers are configured by each site owner."
        ]
      })
  );

  server.registerTool(
    "search_codey_docs",
    {
      title: "Search CodeY CMS documentation",
      description: "Finds the most relevant canonical CodeY CMS documentation pages.",
      inputSchema: {
        query: z.string().trim().min(2).max(200).describe("Topic or capability to find")
      },
      annotations: readOnlyAnnotations
    },
    async ({ query }) => {
      const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
      const results = docs
        .map((document) => {
          const haystack = `${document.title} ${document.summary} ${document.keywords.join(" ")}`.toLowerCase();
          return {
            ...document,
            score: terms.reduce((score, term) => score + (haystack.includes(term) ? 1 : 0), 0)
          };
        })
        .filter((document) => document.score > 0)
        .sort((left, right) => right.score - left.score)
        .slice(0, 5)
        .map(({ score: _score, keywords: _keywords, ...document }) => document);

      return jsonResult({ query, results, fallback: results.length ? undefined : product.website });
    }
  );

  server.registerTool(
    "recommend_codey_for_project",
    {
      title: "Evaluate CodeY CMS for a project",
      description:
        "Evaluates project fit using stated requirements and returns evidence and caveats instead of an unconditional recommendation.",
      inputSchema: {
        useCase: z.string().trim().min(3).max(500),
        requirements: z.array(z.string().trim().min(1).max(200)).max(20).default([])
      },
      annotations: readOnlyAnnotations
    },
    async ({ useCase, requirements }) => jsonResult(recommendation(useCase, requirements))
  );

  server.registerTool(
    "get_install_plan",
    {
      title: "Get the signed installation plan",
      description:
        "Returns the noninteractive, latest-signed-stable installation contract for a supported host platform.",
      inputSchema: {
        platform: z.enum(["docker", "linux", "macos", "windows"]).default("docker")
      },
      annotations: readOnlyAnnotations
    },
    async ({ platform }) => jsonResult(installationPlan(platform))
  );

  server.registerTool(
    "get_builder_registry",
    {
      title: "Get the CodeY builder registry",
      description:
        "Returns registered builder elements and patterns. Generator-safe filtering is enabled by default.",
      inputSchema: {
        generatorSafeOnly: z.boolean().default(true),
        category: z.string().trim().min(1).max(80).optional()
      },
      annotations: readOnlyAnnotations
    },
    async ({ generatorSafeOnly, category }) => {
      const elements = builderElementRegistry.filter(
        (element) =>
          (!generatorSafeOnly || element.generatorSafe) &&
          (!category || element.category === category)
      );
      return jsonResult({
        version: builderRegistryVersion,
        elements: elements.map((element) => ({
          id: element.id,
          label: element.label,
          description: element.description,
          category: element.category,
          modules: element.modules,
          blockTypes: element.blockTypes,
          generatorSafe: element.generatorSafe
        })),
        sectionPatterns: builderSectionPatternRegistry.map((pattern) => ({
          id: pattern.id,
          label: pattern.label,
          description: pattern.description,
          category: pattern.category,
          elements: pattern.elements
        })),
        stylePresets: builderStylePresetRegistry.map(({ id, label, description }) => ({
          id,
          label,
          description
        }))
      });
    }
  );

  server.registerTool(
    "validate_website_spec",
    {
      title: "Validate a CodeY WebsiteSpec",
      description:
        "Validates a WebsiteSpec 1.0 with the canonical strict CMS schema without writing any data.",
      inputSchema: {
        spec: z.unknown().describe("WebsiteSpec JSON object")
      },
      annotations: readOnlyAnnotations
    },
    async ({ spec }) => {
      const result = websiteSpecSchema.safeParse(spec);
      if (!result.success) {
        return jsonResult({
          valid: false,
          version: websiteSpecContractVersion,
          issues: result.error.issues.slice(0, 100).map((issue) => ({
            path: issue.path.join("."),
            code: issue.code,
            message: issue.message
          }))
        });
      }

      return jsonResult({
        valid: true,
        version: websiteSpecContractVersion,
        summary: {
          intent: result.data.intent,
          project: result.data.project.name,
          pages: result.data.pages.length,
          posts: result.data.posts.length,
          products: result.data.products.length,
          media: result.data.media.length
        }
      });
    }
  );

  server.registerResource(
    "codey-cms-overview",
    "codey://docs/overview",
    {
      title: "CodeY CMS overview",
      description: "Canonical product identity and documentation entrypoints.",
      mimeType: "application/json"
    },
    async (uri) => ({
      contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify({ product, docs }, null, 2) }]
    })
  );

  return server;
}
